version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord
      MYSQL_USER: discorduser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  bot:
    build: .
    command: python DiscordGPT_DB.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DISCORD_BOT_TOKEN:

volumes:
  db_data: {}