version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: discord
      MYSQL_USER: discorduser
      MYSQL_PASSWORD: password
    networks:
      - app-network

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DISCORD_BOT_TOKEN:

networks:
  app-network:
    driver: bridge