version: '3.1'

services:

bot:
  build: .
  volumes:
    - .:/app
  depends_on:
    - db
  env_file:
    - .env
  restart: always
  
db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord
      MYSQL_USER: discorduser
      MYSQL_PASSWORD: password
    restart: always