version: '3.1'

services:

  discord_bot:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=your_discord_bot_token_here
    depends_on:
      - db

db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord
      MYSQL_USER: discorduser
      MYSQL_PASSWORD: password
    restart: always